import { test } from '@playwright/test';

test('use auth token', async ({ browser }) => {
    test.setTimeout(120000);
  const context = await browser.newContext({
    extraHTTPHeaders: {
      Authorization: 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYXBwcm92ZXIiLCJyb2xlSWQiOiIyNjQiLCJwZXJtaXNzaW9ucyI6IltcImNhbi12aWV3LWZ0b1wiLFwiY2FuLXJlamVjdC1mdG8tYWZ0ZXItYmlsbC1nZW5lcmF0ZWRcIixcImNhbi1yZWplY3QtZnRvLWJlZm9yZS1iaWxsLWdlbmVyYXRlZFwiLFwiY2FuLWFwcHJvdmUtYWdlbmN5LWRkby1tYXBcIixcImNhbi12aWV3LWhvYS1kZXRhaWxcIixcImNhbi1jaGVjay1hbGxvdG1lbnRcIixcImNhbi1mb3J3YXJkLWJpbGwtdHJlYXN1cnlcIixcImNhbi1yZWdlbmVyYXRlLWNwaW4tZmFpbGVkXCIsXCJjYW4tdmlldy1yZXBvcnRcIixcImNhbi12aWV3LW1hc3Rlci1yZWNvcmRzXCIsXCJjYW4tdmlldy1qaXQtcmVwb3J0XCIsXCJjYW4tY3JlYXRlLWJpbGxcIixcImNhbi1yZWplY3QtZnRvXCIsXCJjYW4tdmlldy1qaXQtYmlsbFwiLFwiY2FuLXZpZXctc3VjY2Vzc2Z1bC1iZW5mLWxpc3RcIixcImNhbi12aWV3LWZhaWxlZC1iZW5mLWxpc3RcIixcImNhbi12aWV3LWJpbGwtd2lzZS1yZXBvcnRcIixcImNhbi12aWV3LXBmbXMtcmVwb3J0XCIsXCJjYW4taW5zZXJ0LWNwaW5cIixcImNhbi12aWV3LWNwaW5cIixcImNhbi11cGRhdGUtZWNzLWNhbmNlbGxhdGlvblwiXSIsImxldmVsIjoiRERPIiwibGV2ZWxJZCI6IjE1NiIsInNjb3BlIjoiQkFBUFJEMDEwIiwic2NvcGVJZCI6IjI1MTY4NyIsIm5hbWVpZCI6IjMyMzM1IiwiZW1haWwiOiJtYW53YXJAZ21haWwuY29tIiwicGhvbmVOdW1iZXIiOiI3MDk4NzA1OTMwIiwibmFtZSI6Ik1hbndhciBIb3NzYWluIiwiY3JlYXRlZF9ieSI6IjE0IiwiZGVzaWduYXRpb24iOiJEZXZlbG9wZXIiLCJ0eXAiOiJhY2MiLCJwdGkiOiIxODA0MiIsImFpZCI6IjYzIiwianRpIjoiMTgwNDMiLCJpYXQiOjE3NTc5MTcwNDksIm5iZiI6MTc1NzkxNzA0OSwiZXhwIjoxNzU3OTE3OTQ5LCJpc3MiOiJXQklGTVNfVVNFUk1BTkFHRU1FTlQiLCJhdWQiOiJXQklGTVNfTU9EVUxFUyJ9.RnZyHUpw9olJtXDW1hqxZNtFYBF5uarojC9pF4Q1OlpM5VKHsSy57HiboXs06AVW51JBpUFCe84FClCTSc4vdQ',
    },
  });
  const page = await context.newPage();
  await page.goto('https://train-ifms.wb.gov.in/ebilling/received-advice');
  await page.screenshot({ path: 'received.png' });
});